### ISSUE TITLE
expand selection is deprecated

### ISSUE THREAD

**Issue by OscarRyz** [mrolla/expand-selection#13]
Trying to use this package pop ups a warning it is deprecated:
![screen shot 2015-08-19 at 4 02 28 pm](https://cloud.githubusercontent.com/assets/656619/9368913/bd077454-468b-11e5-9b6d-76c266446b2f.png)

**Comment by makanikki** [comment]
:+1:

**Comment by mrolla** [comment]
Sorry for the late reply. Atom changed quite a bit of things inside, but before I could actually face the issue I switched back to Vim. You should probably check if any fork solved this.
